try {
anything;
}
catch(__exception__) {
console.log(true);
}

